#!/usr/bin/env node
/**
 * Generates src/version.ts from the current package.json version so the
 * User-Agent and --version flag always match what's published. Runs as
 * part of prebuild. The generated file is committed to git to keep first
 * builds on fresh clones working without side-effects.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const version = pkg.version;

if (typeof version !== "string" || version.length === 0) {
  console.error("package.json is missing a version string");
  process.exit(1);
}

const content = `// Auto-generated by scripts/generate-version.js — do not edit by hand.
// This file is rewritten on every build from package.json.
export const VERSION = ${JSON.stringify(version)};
`;

writeFileSync(resolve(root, "src/version.ts"), content);
console.log(`Wrote src/version.ts with VERSION=${JSON.stringify(version)}`);
